# Site settings
title: Just One Bit
header-img: img/home-bg.png
email: snickers495@gmail.com
copyright_name: snickers495
description: > # this means to ignore newlines until "baseurl:"
  Exploring code through creative writing
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  snickers495
learn_profile: snickers495
email_username: snickers495@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
